service: mosaio-backend


provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 3008
  timeout: 300
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource: "arn:aws:states:us-east-1:915961610259:stateMachine:createMosaic"


plugins:
  - serverless-offline
  - serverless-step-functions


functions:
  dequeue:
    handler: handler.dequeue
    events:
      - schedule: rate(1 minute)


  iterator: 
    handler: handler.iterator

    
  getPhotos:
    handler: handler.getPhotos
    memorySize: 3008
    events:
      - http:
          path: getPhotos
          method: post
          cors: true


  getMosaicPartial:
    handler: handler.getMosaicPartial
    memorySize: 3008
    events:
      - http:
          path: getMosaicPartial
          method: post
          cors: true


  validate:
    handler: handler.validate
    memorySize: 3008
    events:
      - http:
          path: validate
          method: post
          cors: true


  create:
    handler: handler.create
    memorySize: 3008
    events:
      - http:
          path: create
          method: post
          cors: true


  init:
    handler: handler.init
    memorySize: 3008
    events:
      - http:
          path: init
          method: post
          cors: true


  assemble:
    handler: handler.assemble
    memorySize: 3008
    timeout: 300
  
