service: mosaio-backend


provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource: "arn:aws:states:us-east-1:915961610259:stateMachine:createMosaic"


plugins:
  - serverless-offline
  - serverless-step-functions


functions:
  getMosaic:
    handler: handler.getMosaic
    events:
      - http:
          path: mosaic/{mosaicID}
          method: get
          cors: true


  validate:
    handler: handler.validate
    events:
      - http:
          path: validate
          method: post
          cors: true


  create:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
          cors: true


  init:
    handler: handler.init
    events:
      - http:
          path: init
          method: post
          cors: true


  assemble1:
    handler: handler.assemble1
    timeout: 300
  

  assemble2:
    handler: handler.assemble2
    timeout: 300


  assemble3:
    handler: handler.assemble3
    timeout: 300


  assemble4:
    handler: handler.assemble4
    timeout: 300


  assemble5:
    handler: handler.assemble5
    timeout: 300


